### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by m0hammad0099** [ex0dus-0x/brut3k1t#104]
What this error?
Please Help me

![image](https://user-images.githubusercontent.com/20967166/42683663-41a24914-86a3-11e8-9880-02d2c50882f7.png)

**Comment by ex0dus-0x** [comment]
That is a problem with `pip`.
See here: https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi
