### ISSUE TITLE
TRACEBAK 

### ISSUE THREAD

**Issue by krishna774** [ex0dus-0x/brut3k1t#107]
WHEN I START BRUTEFORCE ATTACK IT SHOWA TRACEBACK MOST RECENT CALL LAST PLZ SOLVE ITT

**Comment by ColeShelly** [comment]
Use https://github.com/avramit/Instahack it uses proxies

**Comment by ColeShelly** [comment]
but you might have to change a line in the code ill see if i can find it

**Comment by krishna774** [comment]
Okay plz contact me
8860328508 WhatsApp number
