### ISSUE TITLE
After run installer.py program didn't quit automatically 

### ISSUE THREAD

**Issue by ssysm** [ex0dus-0x/brut3k1t#16]
After run the installer.py and it drop me back to install screen 
![screen shot 2016-12-30 at 8 09 31 pm](https://cloud.githubusercontent.com/assets/11619780/21574969/f17eb8a4-cecb-11e6-9ffb-117582f2f6d1.png)

**Comment by ex0dus-0x** [comment]
It's placed in an infinite loop until `KeyboardInterrupt`. Not a real issue please stop
