### ISSUE TITLE
[*] Checking if username exists... crash

### ISSUE THREAD

**Issue by xdavidhu** [ex0dus-0x/brut3k1t#20]
Installed on a Ubuntu 16.04 64bit VPS, after running the installer script, and installing 'selenium' module manually (because installer haven't done it), it crashes at

[*] Checking if username exists...

Traceback (most recent call last):
  File "brut3k1t.py", line 193, in <module>
    main()
  File "brut3k1t.py", line 172, in main
    if facebookCheck(username) == 1:
  File "src/facebookLib.py", line 19, in facebookCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 150, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by ex0dus-0x** [comment]
This error is a result of not having Firefox installed. 

I'm pretty sure you are not running a graphical interface on a VPS, so I assume you do not have access to the Unity desktop, and therefore a browser is not installed.

**Comment by ex0dus-0x** [comment]
Yes. The reason being that Firefox will open up physically, and selenium will have to interact with it.

Sorry about OS X! I haven't tested enough on OS X, but some people seem to have success with it. I will look into it.

**Comment by xdavidhu** [comment]
I would provide more info about the osx installer, but i dont want to delete my browser again.

But now its asking for the paramiko module (after running the installer script, osx)
"ImportError: No module named paramiko"

**Comment by ex0dus-0x** [comment]
Hopefully `pip` is already installed. If not:

    sudo easy_install pip

Then:

    brew install libffi
    sudo pip install selenium
    sudo pip install -r requirements.txt

I'm assuming the installer crashed, so these are the steps you take to manually install the correct dependencies.

**Comment by xdavidhu** [comment]
All requirement is already satisfied, but still cant import paramiko

**Comment by ex0dus-0x** [comment]
Again, like I have stated before, the OS X installer is sort of broken. 

    brew install libffi
    sudo pip install cryptography
    sudo pip install paramiko

A possible alternative to this is running Ubuntu or Kali Linux on a virtual machine. My apologies, but It will take me time to get access to a Mac again, so do not expect updates to the OS X option in `installer.py` very soon.

**Comment by xdavidhu** [comment]
Probably it is a problem with my setup because i had problem with pip before. 
It weird because all of the requirements are installed but i still cant import those modules.

Anyways thanks for the help, will try it on a virtual machine later.
