### ISSUE TITLE
import error: no mudule named selenium

### ISSUE THREAD

**Issue by zizoo13013** [ex0dus-0x/brut3k1t#21]
in kali linux after installing brut3k1t 
when i type ex : python brut3k1t.py -s instagram -u daafffq -w rock.txt -d 5
it gives me

file "brut3k1t.py" , line 12, in <module>
from facebookLib import * 
file "src/facebookLib.py" , line 3, in <module>
from selenium import webdriver 
import error: no mudule named selenium

tell me please what i should do

**Comment by ex0dus-0x** [comment]
Have you even read the `README` at all? Before you even ask me, that's the first place you should see.

Closed.

**Comment by Deyelk** [comment]
pip install selenium

**Comment by ex0dus-0x** [comment]
pip install selenium

doesn't work on Kali linux. the package is much more functional.

    sudo apt-get install python-selenium
