### ISSUE TITLE
Problem?!?!?!?!?

### ISSUE THREAD

**Issue by Dr-D12345** [ex0dus-0x/brut3k1t#23]
Yeah there seems to be a problem. I think it was the fact you used a Linux my windows cannot handle a program from such a low level operating system.

**Comment by ex0dus-0x** [comment]
If you are planning to run such a binary on Windows, consider utilizing a virtual machine. I don't know about Cygwin support, but if you want to go for that, be my guest.

Currently, the main problems surrounding Windows builds are dependencies, and the hassle of setting up the `$PATH`.
