### ISSUE TITLE
This is no issue but is a great idea for this program

### ISSUE THREAD

**Issue by TwistedLobby** [ex0dus-0x/brut3k1t#27]
I'm wanting to suggest maybe adding a Python GUI version of this?
If you've never worked with Python GUI's this is where I got started
It would be a great idea & pretty cool to see!

https://www.tutorialspoint.com/python/python_gui_programming.htm

**Comment by ex0dus-0x** [comment]
A GUI version has already been developed, not released due to the lack of features.
