### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by Cenaboyle** [ex0dus-0x/brut3k1t#28]
When trying to use the twitter service I always receive the error:
[ ! ] OOPs, something went wrong. Did you terminate the connection? [ ! ]

Massive delays do not help.

**Comment by ex0dus-0x** [comment]
What operating system? Did you run the `installer.py` file? I would also like to know what command you ran.

Massive delays are implemented (specifically in the Instagram service), so that the rate limit can be waited out. However, I am working on alternative methods to not reproduce this trouble.

**Comment by Cenaboyle** [comment]
Running on Kali Linux (Rolling)

Input: 
python brut3k1t.py -s twitter -u MYUSERNAME -w WORDLIST.txt

Output:
[ * ] Username: MYUSERNAME
[ * ] Wordlist: WORDLIST.txt
[ * ] Service: twitter
[ * ] Checking if username exists...
[ * ] Username found! Continuing...
[ ! ] OOPs, something went wrong. Did you terminate the connection? [ ! ]

The error appears once the mobile.twitter.com/login page is loaded in the browser, it feels as if the script cannot detect the login field as if it doesn't exist. I tried -d and using a single line wordfile containing the correct password.

**Comment by ueippp** [comment]
I got the following error:
Traceback (most recent call last):
  File "brut3k1t.py", line 11, in <module>
    from mainLib import *
  File "src/mainLib.py", line 26, in <module>
    import smtplib, argparse, paramiko, skpy, mechanize
ImportError: No module named skpy

Please suggest when using for facebook and gmail. 

Input:  python brut3k1t.py -s smtp -a smtp.gmail.com -u xx@gmail.com -w wordlist.txt -p 25 -d 3

**Comment by ex0dus-0x** [comment]
@Cenaboyle I will look into this and run tests. Please make sure that the necessary troubleshooting techniques have been implemented (i.e running `installer.py` and installing dependencies successfully, using Firefox rather than Iceweasel, and reinstalling `selenium` by uninstalling the pip module, and then installing through the package manager: `apt-get install python-selenium` ). Kali Linux is the optimal operating system for brut3k1t.

**Comment by ex0dus-0x** [comment]
@ueippp Have you run the `installer.py` file yet? Read the README.

**Comment by ueippp** [comment]
Hello ex0dus, 

Yes I did. It ends with this output:

Err http://http.kali.org/kali/ kali-rolling/main libtracker-sparql-1.0-0 amd64 1.10.5-1                                                                                      
  Connection failed
Fetched 7,707 kB in 6min 20s (20.3 kB/s)
Failed to fetch http://http.kali.org/kali/pool/main/m/mesa/libxatracker2_13.0.5-1_amd64.deb  Connection failed
Failed to fetch http://http.kali.org/kali/pool/main/f/firefox-esr/firefox-esr_45.8.0esr-1_amd64.deb  Connection failed
Failed to fetch http://http.kali.org/kali/pool/main/t/tracker/libtracker-sparql-1.0-0_1.10.5-1_amd64.deb  Connection failed
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Installing pip modules
sudo: pip: command not found
Done installing dependences!

Later I am not able to run anything.

**Comment by ueippp** [comment]
FYI installing python-selenium again. Will keep you posted on this.

**Comment by ex0dus-0x** [comment]
@ueippp It seems that you problems having a network connection, at least to the Kali Linux repositories. Try an `apt update` and restart your connection to your home network. 

If it is not a networking issue, try updating your repositories in `/etc/apt/sources.list`. This is mine:

```
# Repositories: Debian and Kali-Rolling

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb http://ftp.us.debian.org/debian/ jessie main contrib non-free

# Source Packages

deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://ftp.us.debian.org/debian/ jessie main contrib non-free
```

and then do another `apt update`.

**Comment by ueippp** [comment]
Hi, 

Sure thanks. I will give it a try and let you know the updates.

**Comment by zeehack** [comment]
i always get with instagram the a message that the password is found however its not the right one .
after 8 or nine attempts it gives me password found but it not really the password ..any ideas 






  _                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x
 
[*] Username: my acc 
[*] Wordlist: /root/Desktop/wordlist.txt 
[*] Service: instagram 
[*] Checking if username exists...
[*] Username found! Continuing...
Using 5 seconds of delay. Default is 1 second
[*] Username: my acc | [*] Password: 123456 | Incorrect!

[*] Username: my acc | [*] Password: 12345678 | Incorrect!

[*] Username: my acc| [*] Password: qwerty | Incorrect!

[*] Username: my acc | [*] Password: 123456789 | Incorrect!

[*] Username: my acc | [*] Password: 12345 | Incorrect!

[*] Username:my accd | [*] Password: 1234 | Incorrect!

[*] Username: my acc | [*] Password: password | Incorrect!

[*] Usernamemy acc [*] Password: 111111 | Incorrect!

[*] Username: my accd | [*] Password: 1234567 | Incorrect!

[*] Username: my accd | [*] Password: dragon | Incorrect!

[*] Username: my acc | [*] Password: 123123 | Incorrect!

[*] Username: my acc| [*] Password: baseball | Incorrect!

[*] Username:my acc | [*] Password: abc123 | Incorrect!

[*] Username: my acc | [*] Password: football | Incorrect!

[*] Username: my acc| [*] Password: monkey | Incorrect!

[*] Username: my acc | [*] Password: letmein | Incorrect!

[*] Username: my acc  | [*] Password: 696969 | Incorrect!

[*] Username: my acc | [*] Password: shadow | Incorrect!

[*] Username: my acc [*] Password: master | Incorrect!

[*] Username: my acc | [*] Password found: 666666

**Comment by zeehack** [comment]
i did everything according to the file attached and i read everything

**Comment by zeehack** [comment]
@ex0dus-0x any one face the same problem , ?

**Comment by LevelAte** [comment]
Did everything how it should be even from the README.txt and every time I try to get into instagram im receiving a true pass from the first choice of any wordlist which is not the password. Any clue how to clear this out and to get it work properly ? I'm using Kali. Got the right repositories and the machinize py and everything, Not getting any errors. It just getting me the first word from the wordlist as a true pass? Appreciate for helping thanks
