### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [ex0dus-0x/brut3k1t#3]
Hello,

is it possible to add a LICENSE file?

**Comment by ex0dus-0x** [comment]
Good idea. MIT seems suitable or this.

**Comment by xorond** [comment]
Hello, looks like you closed the issue but forgot to add the license file.

**Comment by ex0dus-0x** [comment]
I'm still making changes and updates to the code at the moment. DW, the MIT License file is there, I just haven't pushed the repo.
