### ISSUE TITLE
 OOPs, something went wrong. Did you terminate the connection? 

### ISSUE THREAD

**Issue by evaristegal0is** [ex0dus-0x/brut3k1t#31]
OS: Kali 2016.2 64 bit
Input:

> python brut3k1t.py -s twitter -u real_nick -w list.txt -d 5

Output:

> [] Username: real_nick
[] Wordlist: list.txt 
[] Service: twitter 
[] Checking if username exists...
[] Username found! Continuing...
[!] OOPs, something went wrong. Did you terminate the connection? [!]

Any idea?

**Comment by ex0dus-0x** [comment]
Run the `installer.py` again, making sure that all packages are being installed. If you are not getting the correct dependencies, try to update your `/etc/apt/sources.list` to look like mine:

```
# Repositories: Debian and Kali-Rolling

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb http://ftp.us.debian.org/debian/ jessie main contrib non-free

# Source Packages

deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://ftp.us.debian.org/debian/ jessie main contrib non-free

```

**Comment by 5P4D3** [comment]
this issue happens to me.. im using parrot sec 3.5

**Comment by titanicsec** [comment]
This seems to only be an issue with twitter. When the mobile (mbasic) page loads, the script terminates.
However, it works well with Instagram, and the only issue with facebook is an incorrect username - it requires an email address or mobile (cell phone) number. Unfortunately, I can't find an easy way to locate the facebook email, compared to getting the target instagram/twitter handle.

**Comment by ex0dus-0x** [comment]
@titanicsec Not necessary. Passing a username rather than an email is all. 

TODO: Update documentation
