### ISSUE TITLE
Whats this error

### ISSUE THREAD

**Issue by greatfear33** [ex0dus-0x/brut3k1t#35]
python brut3k1t.py -s instagram -u greatfear33 -w /root/Desktop/wordlist.txt -d 5
Traceback (most recent call last):
  File "brut3k1t.py", line 11, in <module>
    from mainLib import *
  File "src/mainLib.py", line 26, in <module>
    import smtplib, argparse, paramiko, skpy, mechanize
ImportError: No module named skpy

**Comment by ex0dus-0x** [comment]
Please read the `README` file. You did not run the `installer.py` file.
