### ISSUE TITLE
I get this error when trying to open installer.py 

### ISSUE THREAD

**Issue by kmostafa599** [ex0dus-0x/brut3k1t#38]
Traceback (most recent call last):
  File "extras/installer.py", line 51, in <module>
    print installer_head
NameError: name 'installer_head' is not defined

**Comment by elohim971** [comment]
the same problem for me... I've been looking for a solution since few 3 days already :(

**Comment by ex0dus-0x** [comment]
My mistake. Rewrote the source code, but did not update the `installer.py` file accordingly. 

I did an update. `git pull` or redownload/reclone

**Comment by elohim971** [comment]
root@elohim971:~/Bureau/brut3k1t/extras# python installer.py

(1) Kali Linux x32/x64
(2) Ubuntu / Parrot OS
(3) Mac OS X / Darwin

>> 1
Traceback (most recent call last):
  File "installer.py", line 58, in <module>
    kali_build()
  File "installer.py", line 3, in kali_build
    print O + "Updating Repositories..." + W
NameError: global name 'O' is not defined

**Comment by elohim971** [comment]
thank you for updating tho :/

**Comment by ex0dus-0x** [comment]
Update again. The `installer.py` that came was not properly built in accordance with the current framework's structure.

**Comment by elohim971** [comment]
Ok it's working thank you very much! You're great!
