### ISSUE TITLE
No module named requests   //  could not find a distribution template for Kali/kali-rolling

### ISSUE THREAD

**Issue by elohim971** [ex0dus-0x/brut3k1t#39]
Hi, I've got a problem (obvisously if I'm here)...

Traceback (most recent call last):
  File "brut3k1t.py", line 2, in <module>
    from src.mainLib import *
  File "/root/Bureau/brut3k1t/src/mainLib.py", line 17, in <module>
    import socket, os, requests
ImportError: No module named requests

I did :
 sudo pip install -r requirements.txt 
and get:
Requirement already satisfied

Could you help me please?

**Comment by elohim971** [comment]
also when I run: 

sudo add-apt-repository universe


Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Kali/kali-rolling

**Comment by ex0dus-0x** [comment]
pip install requests

Add-apt-repository is only available for Ubuntu-based users.

**Comment by elohim971** [comment]
pip install requests
Requirement already satisfied requests: in /usr/local/lib/python2.7/dist-package

Should I find ths dist-package and copy the requests to mainLib.py? if yes, how can I do that?

Thanks a lot for your help

**Comment by elohim971** [comment]
I did an update of requests by downloading them on https://pypi.python.org/pypi/requests

But still the same...

**Comment by ex0dus-0x** [comment]
Uninstall it and install it again with `pip`. It is much more work to manually install it through pypi. Make sure you are running both the program and pip under a Python 2.7 environment.

**Comment by amirreza12121212** [comment]
hi 
i  have big problem in crack instagram
what's this error:
IOError: [Errno 2] No such file or directory: '/usr/lib/firefoxdriver/webdriver.xpi'

**Comment by ex0dus-0x** [comment]
Are on firefox? Please make a new issue and specify your OS and the command that you entered

**Comment by elohim971** [comment]
When you have time can you explain to me what you meant?
"Uninstall it and install it again with pip. It is much more work to manually install it through pypi. Make sure you are running both the program and pip under a Python 2.7 environment."
Uninstall and install the request? How can I do this? pip uninstall requests doesn't work but maybe I'm doing it from the wrong folder?
 And how can I be sure I'm running both progams? When I tape "python" on commands, it's giving me Python 2.7.13, so I guess this is ok.

**Comment by amirreza12121212** [comment]
What's this error:
importerorr: cannot import name incompleteread

**Comment by ex0dus-0x** [comment]
@amirreza12121212 like i have just said, please open a new issue. To fix that issue, `pip install incompleteread`. 

---

The problems that you guys are receiving are operating-system specific. What I recommend is trying to run brut3k1t within `virtualenv`, by actually creating a `virtualenv` container and running the installer.

**Comment by ex0dus-0x** [comment]
Closed for inactivity
