### ISSUE TITLE
I get this error!

### ISSUE THREAD

**Issue by BaraSec** [ex0dus-0x/brut3k1t#4]
Hi, I get this error when trying to brute force Instagram or Facebook:

Traceback (most recent call last):
  File "brut3k1t.py", line 11, in <module>
    from twitterLib import *
  File "src/twitterLib.py", line 2, in <module>
    from selenium import webdriver
ImportError: No module named selenium

**Comment by wermaxta** [comment]
try 
pip install selenium
and what OS you are using

**Comment by ex0dus-0x** [comment]
Do `pip install -r requirements.txt`. 

This will install dependencies. Refer to README for detail and instructions

**Comment by BaraSec** [comment]
Oh I should have thought of that!
Anyway, thanks :)

**Comment by a9v8i** [comment]
[*] Wordlist: wordlist.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 191, in <module>
    main()
  File "brut3k1t.py", line 159, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 20, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7fe264ed6f90>> ignored
 My OS Kali Linux 2016.2

**Comment by ex0dus-0x** [comment]
Make sure `firefox`, `python-selenium`, and `firefoxdriver` is installed. I've included an installer script:

    sudo python installer.py

**Comment by ex0dus-0x** [comment]
Please make a new issue instead of adding to an old one. Will be closed.

**Comment by Wowwowwowwow1** [comment]
I'm running os x mac and I seem to get this problem where geckodriver isn't find firefox?

Traceback (most recent call last):
  File "brut3k1t", line 30, in <module>
    main()
  File "brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/Users/jonathonpage/Desktop/brut3k1t-master/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/Users/jonathonpage/Desktop/brut3k1t-master/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/Library/Python/2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by DeeKoy** [comment]
@Wowwowwowwow1 - it looks like this error is documented in the main README:

If you are getting an error such as Can't load the profile. Profile Dir: /some/path, or 'geckodriver' executable needs to be in PATH., that means that selenium can't find the path to Firefox. You are most likely on a non-Kali Linux operating system, and you chos and here's to fix:

First, sudo apt-get remove python-selenium.

Run the installer.py, this time choosing Ubuntu / Parrot OS i386 or Ubuntu / Parrot OS amd64 depending on your architecture. Running this will ensure that geckodriver will be installed into your PATH.
This sort of issue occurs mostly in non-Kali Linux distributions, even in other Debian-based distros.

**Comment by Wowwowwowwow1** [comment]
Then this comes up (Sorry I'm a total layman) 

sudo apt-get remove python-selenium

sudo: apt-get: command not found

**Comment by DeeKoy** [comment]
Try just,

`sudo apt remove python-selenium`

**Comment by Wowwowwowwow1** [comment]
do you know where I could download java runtime or related program

**Comment by DeeKoy** [comment]
[http://lmgtfy.com/?q=java+runtime+environment+linux](url)

**Comment by DeeKoy** [comment]
http://lmgtfy.com/?q=java+runtime+environment+linux

**Comment by Wowwowwowwow1** [comment]
this will work even though I'm using mac?

**Comment by DeeKoy** [comment]
http://lmgtfy.com/?q=java+runtime+environment+mac

**Comment by Wowwowwowwow1** [comment]
Unable to locate an executable at
"/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/bin/apt"
(-1)
