### ISSUE TITLE
python brut3k1t.py error

### ISSUE THREAD

**Issue by KATRAX21** [ex0dus-0x/brut3k1t#42]
Hi there.Can u please help me with this error .
When i type python brut3k1t.py it gives me this error
Traceback (most recent call last):
  File "brut3k1t.py", line 2, in <module>
    from src.mainLib import *
  File "/root/Desktop/brut3k1t/src/mainLib.py", line 17, in <module>
    import socket, os, requests
ImportError: No module named requests

plz tell me what to do mate <3

**Comment by ex0dus-0x** [comment]
Have you bothered to read the `README`? Please don't make an issue if you haven't read it at all and run the installer. This is a simple `ImportError`. Use pip to install.
