### ISSUE TITLE
/brut3k1t

### ISSUE THREAD

**Issue by 9mt559** [ex0dus-0x/brut3k1t#45]
sing 5 seconds of delay. Default is 1 second
[!] OOPs, something went wrong. Exception: Message: Unable to locate element: {"method":"name","selector":"username"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpu_7Hol/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmpu_7Hol/extensions/fxdriver@googlecode.com/components/driver-component.js:10779)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpu_7Hol/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpu_7Hol/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpu_7Hol/extensions/fxdriver@googlecode.com/components/command-processor.js:12608) [!]

**Comment by ex0dus-0x** [comment]
Please provide more detail. What service? What OS?

**Comment by ZGaRT** [comment]
my to Version 3.22.0 kali linux

**Comment by ex0dus-0x** [comment]
Read the README and follow troubleshooting to see if any of the methods work out.

**Comment by bWt4p6Bfuk** [comment]
on current Kali Linux (4.9), I am getting the same problem. It runs fine for twitter. Not so for instagram. Already tried the steps in the README.

**Comment by ex0dus-0x** [comment]
Will check out. Run the `installer` and see if there are any errors. `selenium` may have been installed improperly.

**Comment by 9mt559** [comment]
Do you have a hack snape chat
في أربعاء، ٢٤ مايو، ٢٠١٧ في ٣:٢٤ ص، كتب Alan <notifications@github.com>:

**Comment by bWt4p6Bfuk** [comment]
installer gives no errors:
`>> 1
Updating Repositories...
Get:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease [30.5 kB]
Get:2 http://mirrors.ocf.berkeley.edu/kali kali-rolling/main amd64 Packages [15.1 MB]
Fetched 15.1 MB in 10s (1,500 kB/s)                                                                                                                                                                               
Reading package lists... Done
Installing essential packages...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.3).
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0e-2).
python-dev is already the newest version (2.7.13-2).
python-setuptools is already the newest version (33.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-selenium is already the newest version (2.53.2+dfsg1-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
firefoxdriver is already the newest version (2.53.2-3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Installing pip modules
Requirement already satisfied: mechanize==0.2.5 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: paramiko==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: selenium==2.53.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: xmpppy==0.5.0rc1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt (line 2))
Requirement already satisfied: cryptography>=1.1 in /usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt (line 2))
Done installing dependences!
`

**Comment by ex0dus-0x** [comment]
@9mt559 Please do not ask that again. Your comment has been removed. 

@bWt4p6Bfuk According to the error, `selenium` is unable to find the `username` element. At this time, I am unable to be able to pinpoint out why this problem is occurring. If `selenium` is installed through `pip`, uninstall it and try again through `apt install python-selenium`.

**Comment by danger1408** [comment]
i have problem please help Traceback (most recent call last):
  File "brut3k1t", line 30, in <module>
    main()
  File "brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/Desktop/brut3k1t/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/Desktop/brut3k1t/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by danger1408** [comment]
help please i have try a a 100 trys help please

**Comment by danger1408** [comment]
i need a help

**Comment by danger1408** [comment]
guys

**Comment by danger1408** [comment]
please replay

**Comment by danger1408** [comment]
helllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllp

**Comment by danger1408** [comment]
hellpp

**Comment by danger1408** [comment]
need a help

**Comment by ex0dus-0x** [comment]
Spamming won't help anything. It just shows that you are desperate. This is an open sourced project for collaborators and hackers to work on for the better of the cybersecurity field. Not for you to be able to hack somebody's account.

Second, this is an issue complete different from the one that is currently being opened. Why can't you create a new one?

Third, have you looked through prior issues? This is something that has been covered before.

Finally, have you even bothered to look at the `README` before even contacting me? I know you haven't because I explicitly covered this issue, since I knew this was prevalent. 

---

This shows me that not only are you immature, impatient, but also nothing but a leech. Programmers and hackers __TRY__ to figure out the problem. Not whine and beg. What's even more sad is the fact that you don't even bother to read the `README` or go through prior issues that have already been closed of this problem.

**Comment by ex0dus-0x** [comment]
It really disgusts me to see how the open-source community within the cybersecurity fields have evolved into script kiddies begging and whining for help. This issue will be archived so that people see the levels of immaturity.

**Comment by danger1408** [comment]
really thanks to make sad thx
