### ISSUE TITLE
smthing about firefoxdriver?

### ISSUE THREAD

**Issue by t9klt0la1a** [ex0dus-0x/brut3k1t#47]
i've installed all the dependencies. It found the user perfectly, then when i get to the login page i get this errors.
![insta](https://cloud.githubusercontent.com/assets/28912324/26382842/4b9bdfc2-3ffd-11e7-9d2d-cc919e855e98.png)
do you know what it could be?
and yes, i've installed firefox driver with "apt-get install firefoxdriver"

**Comment by ex0dus-0x** [comment]
Try utilizing `firefox-esr`, which is the extended support release version of the browser. This is an issue that I have not encountered much with when conducting unit tests, and will look into it and write up a troubleshooting guide.

**Comment by t9klt0la1a** [comment]
im actually using firefox esr :(

**Comment by ex0dus-0x** [comment]
Should be fixed. Problem with `python-selenium` and the `selenium` pip package. Try removing the `selenium` pip package and checking if `python-selenium` is installed through `apt`
