### ISSUE TITLE
Password always found

### ISSUE THREAD

**Issue by vorticalbox** [ex0dus-0x/brut3k1t#49]
It always says "password found" to the first password in the wordlist.

`sudo ./brut3k1t -s facebook -u user -w rockyou.txt

  _                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x
 
[*] Username: username
[*] Wordlist: rockyou.txt 
[*] Service: facebook 
[*] Checking if username exists...
[*] Username found! Continuing...
[*] Username: user | [*] Password found: 123456
`

**Comment by ex0dus-0x** [comment]
Fixed. `git pull` to attain latest commit.

**Comment by vorticalbox** [comment]
tested on most current and still an issue.
