### ISSUE TITLE
halts

### ISSUE THREAD

**Issue by specsnerd007** [ex0dus-0x/brut3k1t#53]
I was trying to brute force my fb account so I made a word list and the program by default uses the first password as the final password regardless of wheather it is correct or incorrect. please tell me if this is a rip off of some program or is it a bug.

**Comment by waelhaydar** [comment]
same issue here... it say password found.... as it only tests first word in the file...

**Comment by adukhan99** [comment]
Same Issue

**Comment by ex0dus-0x** [comment]
Seems as if it is a bug. Will look at source code.

**Comment by ex0dus-0x** [comment]
It seems that when I changed the Facebook target login to `touch.facebook.com` from `iphone.facebook.com`, the `driver.title` for the page source changed, and therefore the `AssertionError` would force a correct password, regardless of the words in the wordlist.

**Comment by waelhaydar** [comment]
okay... are you willing to solve that? and i wonder if you know any way to test VK account..

**Comment by specsnerd007** [comment]
So essentially we have to use the old version of it. Right??

**Comment by ex0dus-0x** [comment]
Fixed. Do a `git update`
