### ISSUE TITLE
still getting the same error

### ISSUE THREAD

**Issue by HackingBegginer527** [ex0dus-0x/brut3k1t#59]
_                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x
 
[*] Username: aaron_yagudayev
[*] Wordlist: eric.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 30, in <module>
    main()
  File "./brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/Desktop/brut3k1t/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/Desktop/brut3k1t/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

root@kali:~/Desktop/brut3k1t# 

still getting the error, please help.

**Comment by ex0dus-0x** [comment]
Manually tar and move the `geckodriver` in dependencies into your `PATH`.

**Comment by HackingBegginer527** [comment]
I know you have given me more instructions on stuff about the gecko driver
but will you kinda guide me through it a little more, I'm a begginer at
this, thanks and have a good day!

**Comment by ex0dus-0x** [comment]
This has already been covered in the README. You can run the installer again, as it will automate the process of moving `geckodriver`. Otherwise, doing it manually is fine.

**Comment by HackingBegginer527** [comment]
HI again,
Im still getting the same geckodriver not in path error let me just show
you all of the code





root@kali:~# cd Desktop
root@kali:~/Desktop# cd brut3k1t
root@kali:~/Desktop/brut3k1t# ls
brut3k1t      docs             installer  README.md         wordlist.txt
core          eric.txt         modules    requirements.txt
dependencies  geckodriver.log  proxy.txt  src
root@kali:~/Desktop/brut3k1t# python installer.pu
python: can't open file 'installer.pu': [Errno 2] No such file or directory
root@kali:~/Desktop/brut3k1t# python installer.py
python: can't open file 'installer.py': [Errno 2] No such file or directory
root@kali:~/Desktop/brut3k1t# python installer

(1) Kali Linux x32/x64
(2) Ubuntu / Parrot OS
(3) Mac OS X / Darwin

(0) Uninstall
>> 2
Updating Repositories...
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File
"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py",
line 109, in __init__
    self.reload_sourceslist()
  File
"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py",
line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in
get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a
distribution template for Kali/kali-rolling
Get:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease [30.5 kB]
Get:2 http://mirrors.ocf.berkeley.edu/kali kali-rolling/main Sources [11.4
MB]
Get:3 http://mirrors.ocf.berkeley.edu/kali kali-rolling/main amd64 Packages
[15.4 MB]
Fetched 26.9 MB in 8s (3,193
kB/s)
Reading package lists... Done
Installing essential packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0f-3).
python-dev is already the newest version (2.7.13-2).
python-setuptools is already the newest version (36.0.1-1).
The following package was automatically installed and is no longer required:
  chromedriver
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 866 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
The following package was automatically installed and is no longer required:
  chromedriver
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 866 not upgraded.
Installing pip modules
Requirement already satisfied: mechanize==0.2.5 in
/usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: paramiko==2.0.2 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests==2.10.0 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: xmpppy==0.5.0rc1 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pyasn1>=0.1.7 in
/usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt
(line 2))
Requirement already satisfied: cryptography>=1.1 in
/usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt
(line 2))
Requirement already up-to-date: selenium in
/usr/local/lib/python2.7/dist-packages
Getting GeckoDriver
tar: geckodriver-v0.13.0-linux32.tar.gz: Cannot open: No such file or
directory
tar: Error is not recoverable: exiting now
Done installing dependences!
root@kali:~/Desktop/brut3k1t# ./installer

(1) Kali Linux x32/x64
(2) Ubuntu / Parrot OS
(3) Mac OS X / Darwin

(0) Uninstall
>> 2
Updating Repositories...
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File
"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py",
line 109, in __init__
    self.reload_sourceslist()
  File
"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py",
line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in
get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a
distribution template for Kali/kali-rolling
Hit:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease
Reading package lists... Done
Installing essential packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0f-3).
python-dev is already the newest version (2.7.13-2).
python-setuptools is already the newest version (36.0.1-1).
The following package was automatically installed and is no longer required:
  chromedriver
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 866 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
The following package was automatically installed and is no longer required:
  chromedriver
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 866 not upgraded.
Installing pip modules
Requirement already satisfied: mechanize==0.2.5 in
/usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: paramiko==2.0.2 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests==2.10.0 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: xmpppy==0.5.0rc1 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pyasn1>=0.1.7 in
/usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt
(line 2))
Requirement already satisfied: cryptography>=1.1 in
/usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt
(line 2))
Requirement already up-to-date: selenium in
/usr/local/lib/python2.7/dist-packages
Getting GeckoDriver
tar: geckodriver-v0.13.0-linux32.tar.gz: Cannot open: No such file or
directory
tar: Error is not recoverable: exiting now
Done installing dependences!
root@kali:~/Desktop/brut3k1t# ./installer

(1) Kali Linux x32/x64
(2) Ubuntu / Parrot OS
(3) Mac OS X / Darwin

(0) Uninstall
>> 1
Updating Repositories...
Hit:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease
Reading package lists... Done
Installing essential packages...
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0f-3).
python-dev is already the newest version (2.7.13-2).
python-setuptools is already the newest version (36.0.1-1).
The following package was automatically installed and is no longer required:
  chromedriver
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 866 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  firefoxdriver
The following NEW packages will be installed:
  python-selenium
0 upgraded, 1 newly installed, 0 to remove and 866 not upgraded.
Need to get 0 B/76.6 kB of archives.
After this operation, 460 kB of additional disk space will be used.
Selecting previously unselected package python-selenium.
(Reading database ... 308984 files and directories currently installed.)
Preparing to unpack .../python-selenium_2.53.2+dfsg1-1_all.deb ...
Unpacking python-selenium (2.53.2+dfsg1-1) ...
Setting up python-selenium (2.53.2+dfsg1-1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  firefoxdriver
0 upgraded, 1 newly installed, 0 to remove and 866 not upgraded.
Need to get 0 B/496 kB of archives.
After this operation, 795 kB of additional disk space will be used.
Selecting previously unselected package firefoxdriver.
(Reading database ... 309081 files and directories currently installed.)
Preparing to unpack .../firefoxdriver_2.53.2-3_amd64.deb ...
Unpacking firefoxdriver (2.53.2-3) ...
Setting up firefoxdriver (2.53.2-3) ...
Installing pip modules
Requirement already satisfied: mechanize==0.2.5 in
/usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: paramiko==2.0.2 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests==2.10.0 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: xmpppy==0.5.0rc1 in
/usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pyasn1>=0.1.7 in
/usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt
(line 2))
Requirement already satisfied: cryptography>=1.1 in
/usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt
(line 2))
Done installing dependences!
root@kali:~/Desktop/brut3k1t# python bru3k1t
python: can't open file 'bru3k1t': [Errno 2] No such file or directory
root@kali:~/Desktop/brut3k1t# python bru3k1t.py
python: can't open file 'bru3k1t.py': [Errno 2] No such file or directory
root@kali:~/Desktop/brut3k1t# ls
brut3k1t      docs             installer  README.md         wordlist.txt
core          eric.txt         modules    requirements.txt
dependencies  geckodriver.log  proxy.txt  src
root@kali:~/Desktop/brut3k1t# python brut3k1t
[!] You have to specify a username AND a wordlist! [!]
root@kali:~/Desktop/brut3k1t# python brut3k1t --help
usage: brut3k1t [-h] [-s SERVICE] [-u USERNAME] [-w PASSWORD] [-a ADDRESS]
                [-p PORT] [-d DELAY] [--proxy PROXY]

Bruteforce framework written in Python

optional arguments:
  -h, --help            show this help message and exit
  -a ADDRESS, --address ADDRESS
                        Provide host address for specified service. Required
                        for certain protocols
  -p PORT, --port PORT  Provide port for host address for specified service.
                        If not specified, will be automatically set
  -d DELAY, --delay DELAY
                        Provide the number of seconds the program delays as
                        each password is tried
  --proxy PROXY         Providing a proxy for anonymization and avoiding
time-
                        outs

required arguments:
  -s SERVICE, --service SERVICE
                        Provide a service being attacked. Several protocols
                        and services are supported
  -u USERNAME, --username USERNAME
                        Provide a valid username for service/protocol being
                        executed
  -w PASSWORD, --wordlist PASSWORD
                        Provide a wordlist or directory to a wordlist
root@kali:~/Desktop/brut3k1t#  ./brut3k1t -s instagram -u aaron_yagudayev
-w wordlist.txt -d 8


  _                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x

[*] Username: aaron_yagudayev
[*] Wordlist: wordlist.txt
[*] Service: instagram
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 30, in <module>
    main()
  File "./brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/Desktop/brut3k1t/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/Desktop/brut3k1t/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py",
line 142, in __init__
    self.service.start()
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py",
line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver'
executable needs to be in PATH.

root@kali:~/Desktop/brut3k1t#



I think it is when i run the installer part since it did look very
differently from the videos, also the video was someone different of mine,
it had 'installer.py' and i just had something else so i had to run it as
'./installer' and ive checked the read.me and i still get the same error:(
how would i be able to install the gecko driver manually or how could i fix
this. Please go over the code and write back as soon as possible, so sorry
to bug you again, have a good day and sorry if i did not capitalize
somethings i am really trying to type this message fast, well again sorry
and please help.

**Comment by ex0dus-0x** [comment]
First of all, why are you running option 2 on the installer when your operating system is clearly Kali Linux, __not__ Ubuntu? Because you ran that option, `selenium` is installed through `pip` instead of `apt`, which is not entirely supported.

I suggest you uninstall the `selenium` pip. I can see that you have already installed `python-selenium`. 
Next time, if you ever run into Python dependencies issues with any application, try to troubleshooting with a `virtualenv`.

Finally, rather than expecting me to fix all of your errors for you, have you even read the `README`, tried what I have suggested for troubleshooting, and then make an issue, instead of utilizing unreliable videos online?

**Comment by HackingBegginer527** [comment]
I see your point and I am very sorry, also sorry for kind of slamming, it's
just that I am really new to all of this and my friend lost his Instagram
password and I am just really trying to get it for him and I'm all
stressed. I am very sorry like I said, I'll try to do better, again thanks
for the help and have a good one:)


On Jul 22, 2017 8:39 AM, "Alan" <notifications@github.com> wrote:

First of all, why are you running option 2 on the installer when your
operating system is clearly Kali Linux, *not* Ubuntu? Because you ran that
option, selenium is installed through pip instead of apt, which is not
entirely supported.

I suggest you uninstall the selenium pip. I can see that you have already
installed python-selenium.
Next time, if you ever run into Python dependencies issues with any
application, try to troubleshooting with a virtualenv.

Finally, rather than expecting me to fix all of your errors for you, have
you even read the README, tried what I have suggested for troubleshooting,
and then make an issue, instead of utilizing unreliable videos online?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ex0dus-0x/brut3k1t/issues/59#issuecomment-317191469>,
or mute the thread
