### ISSUE TITLE
plz i need a solution 

### ISSUE THREAD

**Issue by GoldenHex** [ex0dus-0x/brut3k1t#6]
![screenshot from 2016-12-04 03-27-37](https://cloud.githubusercontent.com/assets/8321366/20863647/513d818e-b9c9-11e6-873f-e8ef3b7c62cf.png)

**Comment by ex0dus-0x** [comment]
`pip install -r requirements.txt` I'm still currently working on development for brut3k1t, so I apologize for the errors.

**Comment by GoldenHex** [comment]
thnx bro no problem :)
