### ISSUE TITLE
'geckodriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by Spr4x** [ex0dus-0x/brut3k1t#61]
Hello,
(I'm a Kali Linux user.)

When i try to do a brute force on an Instagram account, the message i get every time is:

` selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

I've tried to use the:

`sudo apt-get remove python-selenium`

and then installed it as both Ubuntu/parrot once and I've tried to install it as Kali Linux but none of them work, the same message appears every time!

pls help.

**Comment by ex0dus-0x** [comment]
Manually move the `geckodriver` into your `PATH`. The tar is available in the `dependencies` folder.

**Comment by Spr4x** [comment]
Where in the "PATH" should i place it, it doesn't work if the driver is inside the Brut3k1t folder.

i've tried to put the geckodriver in every folder that comes with the Brut3k1t

i'm probably doing this wrong,  i'm new to Linux.

**Comment by ex0dus-0x** [comment]
`/usr/bin` should generally be the `PATH`. This of course, can be checked with `echo $PATH`.

**Comment by Spr4x** [comment]
Problem is solved, thank you for your help!
