### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by keethesh** [ex0dus-0x/brut3k1t#64]
When trying to bruteforce Instagram, it tries some passwords, then when Instagram password-try limit is reached, it simply tells that the password is the last tried. I would suggest using a proxy for bypassing this.

**Comment by barmaanb1383** [comment]
yeah pls use the tor proxy like Pulse script

**Comment by ex0dus-0x** [comment]
While I have promised proxy support, I am currently working on a method to implement proxy chaining.
