### ISSUE TITLE
Apparent issue with selenium

### ISSUE THREAD

**Issue by NamelessGhoul0** [ex0dus-0x/brut3k1t#71]
I have an issue with what appears to be the selenium library, I am not familiar with python so I may be wrong. But either way, I could use some assistance. Thanks for all the work :)

```
Traceback (most recent call last):
  File "./brut3k1t", line 90, in <module>
    main()
  File "./brut3k1t", line 79, in main
    w.execute()
  File "/home/namelessghoul0/brut3k1t/core/web.py", line 39, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/home/namelessghoul0/brut3k1t/core/web.py", line 48, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

**Comment by ex0dus-0x** [comment]
Have you checked to make sure that `geckodriver` is in your `PATH`? Make sure you are also using firefox. Also, what is your operating system?

I will be adding some tweaks that ensure problems occurring with headless browser drivers.

**Comment by NamelessGhoul0** [comment]
Yes, /usr/bin is in PATH. I have noticed 2 things while trying to understand how all this is put together

1: your installer script does not use sudo when moving geckodriver to /usr/bin (maybe instruct users to run as root?)

2: when running geckodriver on its own, I get this error:

```
bash: /usr/bin/geckodriver: cannot execute binary file: Exec format error
```

After this I realized this is a 32bit binary and so I have installed the 64bit binary (easier than fixing lib32)

Once I fixed this, it seemed to run properly, even though I get

```
Error: GDK_BACKEND does not match available displays
```

but that's likely because I'm running this through the Ubuntu subsystem in Windows 10 (there's no display server) and I'll have to install a VM

Thanks for your help, I should be able to take care of the rest myself, but if not I'll ask again :)

**Comment by ex0dus-0x** [comment]
Will do. Writing optimizations as we speak. Hopefully the next set of minor updates will be this weekend, as I have school.
