### ISSUE TITLE
New Error Couldn't Find In Issue section

### ISSUE THREAD

**Issue by rE-b00t** [ex0dus-0x/brut3k1t#73]
My issue is, I installed it just the way it was shown in the tutorial on the script's main page. I did it step by step. everything seems to work fine, I have an up-to-date firefox version. but the main command "./brut3k1t" doesn't work I am pretty sure it is simple for you to solve but I just don't see it my self but it gives me an error in loading selenium module, my ImportError: No module named selenium. Would you please help me.

OS: kali-linux-2017.1-amd64
FireFox: Latest Version

I Install all the modules, read the readme and requirements looked at other issue nothing solved my problem so I thought I might have installed it wrong so I created like 5 more VMs and tried it, still doesn't work so if you could please help me. Thank you for reading have a great day

**Comment by ex0dus-0x** [comment]
`pip install selenium` or `apt install python-selenium`.

This is not an issue, because this problem could've easily been solved by researching how `pip` works, and how to install dependencies in the `requirements.txt` file.
