### ISSUE TITLE
Really Sorry To Bother You, Another Issue

### ISSUE THREAD

**Issue by rE-b00t** [ex0dus-0x/brut3k1t#74]
thank you so much for the response to my other issue, but now I am getting something else, i saw someone else saying that they have the same issue after it says checking if username exists, and in your troubleshooting it says that if you get this issue it means that your most likely on a non Kali Linux machine but i am on Kali Linux, still doesn't work, it is the issue that says that the gekodriver needs to be in path but it is in the directory and it is not detecting it can you please, help with that, because i am new to your scripts in general so i don't know what kind of ways you use to script them, but sorry again to 
bother you
***NOTE PLEASE READ***
can you please contact me on any of this social media because i need the script to work or i might lose really important info.

Skype: Fadi2003 (picture: white wall)
Discord: Fadik2003#0368

**Comment by rE-b00t** [comment]
I know it says that I have to place it in the dir but what exactly doi have to place, and where do I get it from?

**Comment by rE-b00t** [comment]
i just tried another way for the issue in troubleshooting to choose the parrot OS still dosnt work but it giving me another issue that says selenium.coomon.exeptions.WebDriverException: Unable to find a matching set of capabilities please help me i am on the edge. i dont have much time to get my info back

**Comment by rE-b00t** [comment]
it looks like there is an issue in the installer, I just noticed that all the requirements package names are changed so, you might have to fix to the up-to-date names because it keeps saying for each package E: cannot locate "name of package"

**Comment by ex0dus-0x** [comment]
`selenium.coomon.exeptions.WebDriverException` is an issue that has been apparent with Firefox versioning. Source: https://stackoverflow.com/questions/43713445/selenium-unable-to-find-a-matching-set-of-capabilities-despite-driver-being-in

As for the `E: cannot locate "name of package"`, issue, __THAT__ is an issue with your package manager. The dependencies specified in the `installer` are universal amongst most Linux distributions.
In fact, running it on my own machine doesn't yield the same result that you had.

The `installer` also ensures that `geckodriver` is in the right place. If for some reason it is not in the right place and you are to do it manually, you should be getting it from [here](https://github.com/mozilla/geckodriver/releases/) and moving the executable into your `PATH`.

Please do not ask me to contact you on social media. `brut3k1t` was not created for the sole purpose of hacking yours or someone else's account.
