### ISSUE TITLE
Error with xmpp on parrot

### ISSUE THREAD

**Issue by Virgula0** [ex0dus-0x/brut3k1t#75]
After installation with ./installer on parrot os and installing requirements with pip all is done.
But when I try to open the program an error with xmpp import occurred...

> ┌─[root@parrot]─[/home/xxxx/Desktop/brut3k1t]
└──╼ #./brut3k1t 
Traceback (most recent call last):
  File "./brut3k1t", line 2, in <module>
    from src import *
  File "/home/xxxx/Desktop/brut3k1t/src/__init__.py", line 2, in <module>
    from . import main
  File "/home/xxxx/Desktop/brut3k1t/src/main.py", line 8, in <module>
    from xmpp import *
ImportError: No module named xmpp

How to resolve?

**Comment by Virgula0** [comment]
'Collecting xmpp

Could not find a version that satisfies the requirement xmpp (from versions:) No matching distribution found for xmpp

**Comment by ex0dus-0x** [comment]
`pip install xmppy` is the correct command.

If you have not read the `README`, you should have ran the `installer` to install necessary dependencies.

**Comment by Virgula0** [comment]
did it, and it shown me the same error... I already installed all of your dependencies I can't install only this....

**Comment by ex0dus-0x** [comment]
Apologies: the correct dependency name is `xmpppy`; it is confusing because it contains an extra.

**Comment by Virgula0** [comment]
I did pip install xmpppy
after this I try to execute but...

> python3 brut3k1t
  File "brut3k1t", line 27
    print R + "[!] You have to specify a username AND a wordlist! [!]" + W
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print R + "[!] You have to specify a username AND a wordlist! [!]" + W)?

and if I try with python and not python3:

> python brut3k1t
Traceback (most recent call last):
  File "brut3k1t", line 2, in <module>
    from src import *
  File "/home/virgula/Desktop/brut3k1t/src/__init__.py", line 2, in <module>
    from . import main
  File "/home/virgula/Desktop/brut3k1t/src/main.py", line 8, in <module>
    from xmpp import *
ImportError: No module named xmpp

appears again the error of xmpp....

**Comment by ex0dus-0x** [comment]
When you run `pip`, it is most likely install the package for `python 3`, not `python 2`. You can check as so:

    pip --version
    pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

My `pip` installer runs for `2.7`. 

To fix this:

    pip2.7 install xmpppy

And then execute `brut3k1t` as you would with `python`.

**Comment by Virgula0** [comment]
>pip --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python3.6)

> pip3.6 install xmpppy
basi: pip3.6: command not found

I don't understand....

**Comment by ex0dus-0x** [comment]
Attempt running with 2.7, because brut3k1t is built with 2.7. Execute with ‘pip2.7’ instead

**Comment by Virgula0** [comment]
It seems working now thank you. A final question... is currently working cracking for gmail accounts of others email providers?

**Comment by ex0dus-0x** [comment]
Are you using the SMTP protocol for brut3k1t? If yes, try different ports for SMTP that Google Mail is utilizing.
