### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mehdi112233** [ex0dus-0x/brut3k1t#78]
when tipe installer in the dos .say installer is not recognized as an internal or external command.operable or batch file...............plse help me

**Comment by ex0dus-0x** [comment]
Please note that `brut3k1t` is optimal for Unix-based shells. You are attempting to run it in a Windows environment.

**Comment by hvze** [comment]
use LXSS.

**Comment by Juniorn1003** [comment]
I made a better version of Facebook/Twitter/Instagram Bruteforce script, come check it out.
brut3-k1t is not ready for bruteforcing yet, it has no proxy at all.
https://github.com/Juniorn1003/Faitagram
