### ISSUE TITLE
brutekit issue

### ISSUE THREAD

**Issue by karmaholic** [ex0dus-0x/brut3k1t#79]
hello ex0dus i know you probably don't have time for this but i was just looking for some help when i try to bruteforce my old twitter account it only comes up with 66 digit password and it wont spam brute force like i see in tutorials it also says "Cant find libssl-dev" file do you have any suggestions on how to fix this

**Comment by ex0dus-0x** [comment]
`sudo apt install libssl-dev`

**Comment by a7trt-wiak** [comment]
Sorry, I can't make it tonight.   
  
  
  

  
  

  
  
>

**Comment by karmaholic** [comment]
i did but it says missing still

**Comment by hvze** [comment]
What OS are you running?

**Comment by karmaholic** [comment]
i have tried everyone hvze what do you recommend

**Comment by Juniorn1003** [comment]
What OS are you running

**Comment by hvze** [comment]
What OS are you running currently, I can help you fix it if you tel em what you'e running. I am not going to suggest something so you can JUST use this tool.

**Comment by karmaholic** [comment]
im using the kali os its just kali linux
