### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by bedoe** [ex0dus-0x/brut3k1t#80]
Actually... everytime I try to use a command it shows me this window
![kk](https://user-images.githubusercontent.com/34168917/33529184-145e4abc-d87e-11e7-862a-575b7a27065a.png)
Any suggestions?

**Comment by Juniorn1003** [comment]
Did you run the install.py?

**Comment by Juniorn1003** [comment]
I made a better version of Facebook/Twitter/Instagram Bruteforce script, come check it out.
brut3-k1t is not ready for bruteforcing yet, it has no proxy at all.
https://github.com/Juniorn1003/Faitagram
