### ISSUE TITLE
/brut3k1t

### ISSUE THREAD

**Issue by splendid31** [ex0dus-0x/brut3k1t#81]
pls i need your help guys
am not sure if you answered this issue before, because i search and i dont have solution for my problem
i have firefox esr 52.5.0 and am using kali linux rolling 2017.3
this is my problem when i use brut3k1t .
![brut](https://user-images.githubusercontent.com/31418690/34075813-7d781d44-e2d2-11e7-8b36-4a5fb8f16356.png)

**Comment by Juniorn1003** [comment]
I made a better version of Facebook/Twitter/Instagram Bruteforce script, come check it out.
brut3-k1t is not ready for bruteforcing yet, it has no proxy at all.
https://github.com/Juniorn1003/Faitagram
