### ISSUE TITLE
Error on Twitter Login - Obsolete URL - Fix pls

### ISSUE THREAD

**Issue by MartinRR97** [ex0dus-0x/brut3k1t#83]
When Brut3k1t try to work on Twitter, it access to this link: mobile.twitter.com/session/new (Ill put a image) that doesn´t work anymore, the screen get freeze. Someone can help? Im new and spanish btw, I justwana learn! thx

![br](https://user-images.githubusercontent.com/35665716/35197617-14c9ea80-fee2-11e7-9f25-eecac2c9c35e.jpg)

**Comment by ex0dus-0x** [comment]
The URL is working. However, it seems that Twitter is now rendering their mobile page for a longer period of time. Try setting a longer delay.
