### ISSUE TITLE
 OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by MeHraTt** [ex0dus-0x/brut3k1t#96]
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/Desktop/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/Desktop/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by ItzL3op4rd** [comment]
try: pip install -r requirements.txt 
btw brutek1t tool is not working for gmail, and instagram block the ip after some try.

**Comment by abkreno2530** [comment]
@ItzL3op4rd  
Peace, mercy and blessings of God
I first thank you for your interest in answering the question. Secondly, I have the same problem and when I tried to write the matter that I mentioned above, I tried to find a solution but I could not hope with all my heart to help me and thank you very much.
________________________________________
root@Abkreno:~/brut3k1t# pip install -r requirements.txt
Requirement already satisfied: asn1crypto==0.24.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied: cffi==1.11.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (1.11.4)
Requirement already satisfied: cryptography==2.1.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (2.1.4)
Requirement already satisfied: enum34==1.1.6 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (1.1.6)
Requirement already satisfied: idna==2.6 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (2.6)
Requirement already satisfied: ipaddress==1.0.19 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (1.0.19)
Requirement already satisfied: mechanize==0.2.5 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7)) (0.2.5)
Requirement already satisfied: paramiko==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (2.0.2)
Requirement already satisfied: pyasn1==0.4.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9)) (0.4.2)
Requirement already satisfied: pycparser==2.18 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (2.18)
Requirement already satisfied: requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (2.10.0)
Requirement already satisfied: selenium==3.9.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (3.9.0)
Requirement already satisfied: six==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (1.11.0)
Requirement already satisfied: xmpppy==0.5.0rc1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (0.5.0rc1)
mitmproxy 0.18.2 has requirement cryptography<1.6,>=1.3, but you'll have cryptography 2.1.4 which is incompatible.
mitmproxy 0.18.2 has requirement pyasn1<0.2,>=0.1.9, but you'll have pyasn1 0.4.2 which is incompatible.
mitmproxy 0.18.2 has requirement six<1.11,>=1.10, but you'll have six 1.11.0 which is incompatible.
